FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn -q dependency:resolve
COPY src ./src
RUN mvn -q package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /root/
COPY --from=builder /app/target/{{.Config.Name}}-1.0.0.jar app.jar
CMD ["java","-jar","app.jar"]
