name: Generate Task Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.7'

      - name: Build CLI
        run: go build -o mcpcli ./cmd/mcpcli

      - name: Run generate command
        run: |
          ./mcpcli generate sample-project \
            --language golang \
            --transport stdio \
            --output ./generated \
            --force

      - name: Build generated project
        run: |
          cd generated
          go mod tidy
          go build ./...

      - name: Generate Java project
        run: |
          ./mcpcli generate sample-java \
            --language java \
            --transport stdio \
            --output ./generated-java \
            --force

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build generated Java project
        run: |
          cd generated-java
          mvn -B package
